# Generated by Django 3.2.12 on 2023-07-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('school', models.CharField(max_length=20)),
                ('theclass', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField(max_length=13)),
            ],
        ),
    ]
