# Generated by Django 3.2.12 on 2023-07-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shackro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.IntegerField(),
        ),
    ]
